name: Automatic Code Review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 모든 히스토리를 가져옵니다

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython python-dotenv transformers torch

    - name: Run code review
      env:
        MODEL_NAME: ${{ secrets.MODEL_NAME }}
        HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      run: python code_review.py

    - name: Create comment
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs')
          const reviewOutput = fs.readFileSync('review_output.txt', 'utf8')
          if (github.event_name === 'pull_request') {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: reviewOutput
            })
          } else if (github.event_name === 'push') {
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              commit_sha: context.sha,
              body: reviewOutput
            })
          }
